[build]
    command = "npm run build"
    functions = "functions/"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[redirects]]
    from = "/print"
    to = "/.netlify/functions/print"
    status = 200
    